Repository jenkins-infra/docker-openvpn, pull requests merged in 2025-04, with the labels that each got.

#397 feat(ccds): add route for azure.ci.jenkins.io
  cert/ccd/private/abayer
  cert/ccd/private/danielbeck
  cert/ccd/private/dduportal
  cert/ccd/private/jayfranco_cb
  cert/ccd/private/kevingrdj
  cert/ccd/private/kohsuke
  cert/ccd/private/krisstern
  cert/ccd/private/markewaite
  cert/ccd/private/notmyfault
  cert/ccd/private/smerle
  cert/ccd/private/swapna_01
  cert/ccd/private/timja
  cert/ccd/private/wfollonier
  config.yaml
Labels: enhancement, ccd

#402 chore(GHA) use `ubuntu-latest` runner for Release Drafter
  .github/workflows/release-drafter.yaml
Labels: skip-changelog, skip-ci

#343 chore: separate updatecli to its own pipeline
  updatecli/values.yaml
Labels: chore, updatecli

#405 chore(Jenkinsfile_k8s): Remove automaticSemanticVersioning from script call
  Jenkinsfile_k8s
Labels: chore

#406 fix(ccd) set up jayfranco_cb routes
  cert/ccd/private/jayfranco_cb
Labels: bug
